name: GitHub Actions demo
on:
  push:
    branches: [ main ]
    paths-ignore: {.github/**]
  pull-request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow-dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by event: ${{ github.event.name }}"
          echo "The name of your branch is: % {{ github.ref }} and your repository is ."
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
